# Generated by Django 3.0 on 2020-07-17 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cars',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model', models.CharField(max_length=60, verbose_name='Model')),
                ('manufacturer', models.CharField(max_length=60, verbose_name='Manufacturer')),
                ('transmission', models.SmallIntegerField(choices=[(1, 'Mechanical'), (2, 'Automatic'), (3, 'Robotic')], default=0, verbose_name='Transmission')),
                ('release_year', models.IntegerField(verbose_name='Release year')),
                ('colors', models.CharField(max_length=20, verbose_name='Color')),
                ('photo', models.ImageField(blank=True, upload_to='photos', verbose_name='Photo')),
                ('description', models.TextField(default=None)),
            ],
            options={
                'verbose_name': 'Автомобиль',
                'verbose_name_plural': 'Автомобили',
            },
        ),
    ]
