# Generated by Django 3.0 on 2020-07-17 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cars',
            name='transmission',
            field=models.SmallIntegerField(choices=[(1, 'mechanic'), (2, 'automatic'), (3, 'robotic')], default=0, verbose_name='Transmission'),
        ),
    ]
