# Generated by Django 3.0 on 2020-07-18 16:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20200718_1943'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cars',
            name='description',
        ),
    ]
