# Generated by Django 3.0 on 2020-07-18 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_remove_cars_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cars',
            name='colors',
            field=models.CharField(max_length=30, verbose_name='Color'),
        ),
        migrations.AlterField(
            model_name='cars',
            name='manufacturer',
            field=models.CharField(max_length=50, verbose_name='Manufacturer'),
        ),
        migrations.AlterField(
            model_name='cars',
            name='model',
            field=models.CharField(max_length=50, verbose_name='Model'),
        ),
    ]
